# Generated by Django 3.2.16 on 2025-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technol_parts_apps', '0005_recipeingredient_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tag',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, through='technol_parts_apps.RecipeTag', to='technol_parts_apps.Tag'),
        ),
    ]
