# Generated by Django 3.2.16 on 2025-08-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technol_parts_apps', '0006_auto_20250724_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteAndShoppingListModel',
        ),
    ]
