# Generated by Django 3.2.16 on 2025-08-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technol_parts_apps', '0007_delete_favoriteandshoppinglistmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('user',), 'verbose_name': 'Лист избранного', 'verbose_name_plural': 'Листы избранного'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('user',), 'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('-date',), 'verbose_name': 'Количество ингридиентов', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'ordering': ('tag',), 'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецептов'},
        ),
        migrations.AlterModelOptions(
            name='shopping',
            options={'ordering': ('user',), 'verbose_name': 'Лист покупок', 'verbose_name_plural': 'Листы покупок'},
        ),
    ]
