# Generated by Django 3.2.16 on 2025-08-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technol_parts_apps', '0010_auto_20250804_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ('date',), 'verbose_name': 'Количество ингридиентов', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
    ]
