# Generated by Django 3.2.16 on 2025-08-04 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technol_parts_apps', '0011_alter_recipeingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Длительность готовки не может быть меньше 1'), django.core.validators.MaxValueValidator(32000, message='Длительность готовки не может быть больше 32000')], verbose_name='Время готовки'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиента не может быть меньше 1'), django.core.validators.MaxValueValidator(32000, message='Количество ингредиента не может быть больше 32000')], verbose_name='Количественный показатель ингридиента'),
        ),
    ]
