# Generated by Django 3.2.16 on 2025-08-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technol_parts_apps', '0012_auto_20250804_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetag',
            options={'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецептов'},
        ),
    ]
