# Generated by Django 3.2.16 on 2025-08-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technol_parts_apps', '0013_alter_recipetag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipetag',
            options={'ordering': ('tag',), 'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецептов'},
        ),
    ]
