# Generated by Django 4.2.23 on 2025-07-14 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_lasst_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Поле 'username' должно состоять только из букв, цифр и символов: '@', '.', '+', '-', '_'", regex='^[\\w.@+-]+\\Z'), django.core.validators.RegexValidator(inverse_match=True, message='Нельзя создать пользователя с никнеймом "me"', regex='^me$')], verbose_name='Никнейм пользователя'),
        ),
    ]
